name: Build

on: [push]

jobs:
  build:
    name: Build with Hugo
    runs-on: ubuntu-latest

    env:
      GCS_BUCKET: ${{ secrets.GCS_BUCKET }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      uses: docker://forestryio/hugo:node12
      env:
        HUGO_VERSION: 0.79.1
      with:
        # Interestingly, a shell-style subst also works here, but it's not GH Actions doing it, so my theory is that it's passed verbatim to docker, but the entrypoint is bash, which evalates this string as a shell expression and does the expansion cause it's in the runner's env
        args: hugo --enableGitInfo -b https://${{ secrets.GCS_BUCKET }} -s . -d public

    - name: Stash
      uses: actions/upload-artifact@v2
      with:
        name: site
        path: public/
        if-no-files-found: error

    # TODO put build command into an npm script, use yarn run here and forestry (see forestry for command ref)
