name: Build and Publish

on:
  push:
    branches:
      - main

jobs:
  build_and_publish:
    name: Build and Publish to GCS
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

      # GH's `ubuntu-latest` has a fair few packages in it...
    - name: Install dependancies
      run: yarn install

    - name: Build
      uses: docker://forestryio/hugo:node12
      env:
        HUGO_VERSION: 0.79.1
      with:
        # Have to yarn install inside this container, because it's this step that needs node_modules, and it runs in a container, not a "native" action step, the host's software isn't available.
        # Interestingly, a shell-style subst also works here, but it's not GH Actions doing it, so my theory is that it's passed verbatim to docker, but the entrypoint is bash, which evalates this string as a shell expression and does the expansion cause it's in the runner's env
        args: build/build.sh ${{ secrets.GCS_BUCKET }}

    - name: Setup gcloud / gsutil
      uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        project_id: ${{ secrets.GCP_PROJECT }}
        service_account_key: ${{ secrets.GCS_SA_KEY }}
        export_default_credentials: true

    # Could `hugo deploy` but for a start that would mean hard-coding (or frobbing) the bucket URL into the Hugo config file
    - name: Deploy
      env:
        GCS_BUCKET: ${{ secrets.GCS_BUCKET }}
      run: |-
        gsutil -m rsync -R public gs://$GCS_BUCKET
