name: Publish

on:
  push:
    branches:
      - main

jobs:
  build_and_publish:
    name: Build and Publish to GCS
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      uses: docker://forestryio/hugo:node12
      env:
        HUGO_VERSION: 0.79.1
      with:
        # Interestingly, a shell-style subst also works here, but it's not GH Actions doing it, so my theory is that it's passed verbatim to docker, but the entrypoint is bash, which evalates this string as a shell expression and does the expansion cause it's in the runner's env
        args: build/build.sh ${{ secrets.GCS_BUCKET }}

    # TODO put build command into an npm script, use yarn run here and forestry and make

    - name: Setup gcloud / gsutil
      uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        project_id: ${{ secrets.GCP_PROJECT }}
        service_account_key: ${{ secrets.GCS_SA_KEY }}
        export_default_credentials: true

    - name: Deploy
      env:
        GCS_BUCKET: ${{ secrets.GCS_BUCKET }}
      run: |-
        gsutil -m rsync -R public gs://$GCS_BUCKET
