name: Publish

on:
  workflow_run:
    workflows: ["Build"]
    branches: [main]
    types:
      - completed

jobs:
  build:
    name: Publish to GCS
    runs-on: ubuntu-latest

    env:
      GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
      GCS_BUCKET: ${{ secrets.GCS_BUCKET }}

    steps:
    - name: Unstash
      uses: actions/download-artifact@v2
      with:
        name: site
        path: public

    - name: Setup gcloud / gsutil
      uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        project_id: ${{ secrets.GCP_PROJECT }}
        service_account_key: ${{ secrets.GCS_SA_KEY }}
        export_default_credentials: true

    - name: Deploy
      run: |-
        gsutil -m rsync -R public gs://$GCS_BUCKET
