name: Publish

on:
  push:
    branches:
      - main

jobs:
  build_and_publish:
    name: Build and Publish to GCS
    runs-on: ubuntu-latest

    env:
      GCS_BUCKET: test.mt165.training

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup gcloud / gsutil
      uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        project_id: domains-cceouond
        service_account_key: ${{ secrets.GCS_SA_KEY }}
        export_default_credentials: true

    - name: Build
      run: |-
        hugo build -b https://$GCS_BUCKET -s . -d public

        # TODO parameteriese

    # TODO put build command into an npm script, use yarn run here and forestry (see forestry for command ref)
    # TODO status badge
    # TODO go home TODO go home TODO go home TODO go home

    - name: Deploy
      run: |-
        gsutil -m rsync -R public gs://$GCS_BUCKET
