name: Publish

on:
  push:
    branches:
      - main

jobs:
  build_and_publish:
    name: Build and Publish to GCS
    runs-on: ubuntu-latest

    env:
      GCP_PROJECT: {{ secrets.GCP_PROJECT }}
      GCS_BUCKET: {{ secrets.GCS_BUCKET }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      uses: docker://forestryio/hugo:node12
      env:
        HUGO_VERSION: 0.79.1
      with:
        args: hugo -b https://$GCS_BUCKET -s . -d public

    # TODO put build command into an npm script, use yarn run here and forestry (see forestry for command ref)
    # TODO Separate stages into jobs, depend, badges

    - name: Setup gcloud / gsutil
      uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        project_id: $GCP_PROJECT
        service_account_key: ${{ secrets.GCS_SA_KEY }}
        export_default_credentials: true

    - name: Deploy
      run: |-
        gsutil -m rsync -R public gs://$GCS_BUCKET
